### Testar o Parquimetro

GET  http://localhost:8080/tiquete
content-type: application/json

{
  "id": 1
}
###  "valor": 10.5,
###  "dataPagamento": "2024-01-23",
###  "horaEntrada": "10:00:00",
###  "horaSaida": "12:00:00",
###  "tipoPagamento": "CREDITO",
###  "quantidadeHoras": "",
###  "tarifaDescricao": "FIXO",